# Generated by Django 5.0.4 on 2024-12-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Project Title')),
                ('description', models.TextField()),
                ('images', models.TextField(max_length=1000)),
                ('technologies', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
