# Use an official Python runtime as a parent image
FROM python:3-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY http_server.py .

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME=http_server

# Run app.py when the container launches
CMD ["python", "http_server.py"]