# Eine offizielle Python-Laufzeitumgebung als übergeordnetes Image verwenden
FROM python:3-slim

# Einstellen des Arbeitsverzeichnisses im Container
WORKDIR /app

# Den Inhalt des aktuellen Verzeichnisses in den Container unter / app kopieren
COPY . /app
COPY matrix.thrift /app


# Port 12345 für die Welt außerhalb dieses Containers verfügbar machen
EXPOSE 12345 12346 12347

# app.py beim Starten des Containers ausführen
CMD ["python", "controller.py"]

# Installiere die Abhängigkeit ping
RUN apt-get update && apt-get install -y iputils-ping && \
    rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y thrift-compiler

RUN pip install thrift

RUN mkdir -p gen_py_matrix

RUN thrift --gen py --out gen_py_matrix matrix.thrift

RUN pip install paho-mqtt
