"""praktikum_6

Revision ID: 39ae3140d696
Revises: 671fad5bdd28
Create Date: 2024-12-12 14:13:14.081010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ae3140d696'
down_revision = '671fad5bdd28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Change the size of the description column in pizza_type
    op.alter_column(
        'pizza_type',  # table name
        'description',  # column name
        type_=sa.String(length=60),  # new type
        existing_type=sa.String(length=30),  # existing type
        nullable=False  # assuming the column should remain non-nullable
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert the change in the downgrade function
    op.alter_column(
        'pizza_type',  # table name
        'description',  # column name
        type_=sa.String(length=30),  # revert to old type
        existing_type=sa.String(length=60),  # existing type
        nullable=False  # assuming the column should remain non-nullable
    )
    # ### end Alembic commands ###
