"""my_new_feature

Revision ID: 671fad5bdd28
Revises: 40ae859bce90
Create Date: 2024-11-04 14:48:14.555383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671fad5bdd28'
down_revision = '40ae859bce90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
